keyfile = "~/.ssh/id_rsa"
gateway_instance_type = "4C-16GB"
tank_instance_type = "2C-8GB"
cassandra_instance_type = "2C-8GB"
openstack_username = "fzouhar"
keypair = "fzouhar"
openstack_project = "fzouhar"
# openstack_password = ""
docker_username = "ci-runner"
docker_password = "Q3o7Nwq-qjS6tmKquGxv"
tank_node_count = 5
cassandra_node_count = 5
tank_disk_size = 25
cassandra_disk_size = 25